[package]
name = "rivatuner"
version = "0.1.0"
authors = ["Christopher Serr <christopher.serr@gmail.com>"]

[dependencies]
winapi = "0.2.8"
kernel32-sys = "0.2.2"
libc = "0.2.18"

[lib]
crate-type = ["rlib", "cdylib", "staticlib"]
